// Package entity provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package entity

// BaseSuccess defines model for BaseSuccess.
type BaseSuccess struct {
	Code    string      `json:"code"`
	Data    interface{} `json:"data"`
	Message string      `json:"message"`
}

// Error defines model for Error.
type Error struct {
	Code    string       `json:"code"`
	Edited  bool         `json:"edited"`
	Error   *interface{} `json:"error,omitempty"`
	Message string       `json:"message"`
}

// HealthCheckResponse defines model for healthCheckResponse.
type HealthCheckResponse struct {
	Healthy bool `json:"healthy"`
}

// N400 defines model for 400.
type N400 = Error

// N401 defines model for 401.
type N401 = Error

// N403 defines model for 403.
type N403 = Error

// N404 defines model for 404.
type N404 = Error

// N500 defines model for 500.
type N500 = Error

// Success defines model for success.
type Success = BaseSuccess

// DummyEndpointParams defines parameters for DummyEndpoint.
type DummyEndpointParams struct {
	// Type Error type
	Type *string `form:"type,omitempty" json:"type,omitempty" validate:"required"`
}

// DummyEndpointPostJSONBody defines parameters for DummyEndpointPost.
type DummyEndpointPostJSONBody struct {
	Type *string `json:"type,omitempty" validate:"required"`
}

// DummyEndpointPostJSONRequestBody defines body for DummyEndpointPost for application/json ContentType.
type DummyEndpointPostJSONRequestBody DummyEndpointPostJSONBody
