// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	. "cdd-go-boilerplate/internal/entity"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /dummy/sample)
	DummyEndpoint(ctx echo.Context, params DummyEndpointParams) error

	// (POST /dummy/sample)
	DummyEndpointPost(ctx echo.Context) error

	// (GET /healthcheck)
	HealthCheck(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DummyEndpoint converts echo context to params.
func (w *ServerInterfaceWrapper) DummyEndpoint(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DummyEndpointParams
	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", ctx.QueryParams(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DummyEndpoint(ctx, params)
	return err
}

// DummyEndpointPost converts echo context to params.
func (w *ServerInterfaceWrapper) DummyEndpointPost(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DummyEndpointPost(ctx)
	return err
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/dummy/sample", wrapper.DummyEndpoint, options.OperationMiddlewares["dummyEndpoint"]...)
	router.POST(options.BaseURL+"/dummy/sample", wrapper.DummyEndpointPost, options.OperationMiddlewares["dummyEndpointPost"]...)
	router.GET(options.BaseURL+"/healthcheck", wrapper.HealthCheck, options.OperationMiddlewares["healthCheck"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FbBcqM4EP0VqneP2JC196JbspuqzWGrUptjygcZ2kZZkBSp8YRx8e9TLSDYDjPOTJI5zQmMnl6/Vnc/",
	"eQ+ZqazRqMmD2INDb432GH4s05QfmdGEmvhVWluqTJIyOnnwRvM3nxVYSX773eEGBPyWjJxJt+qTa+eM",
	"g7ZtY8jRZ05ZJgEBa5lHDh9r9BRhB4phmV58fORay5oK49RnzA9DLz4+9Ma4tcpz1F3E5cdH1Iaijan1",
	"QaZ//ozyKk3otCwjadXMo9uhGxX4OsvQ+3dTcSU93vWck63mMepjRkOnA+N6AuY/5BB7sM5YdKSwV5kj",
	"P6mxCAI8OaW3nEkuidW1MVTovdxOodoYuNGVwxzEfcc14nuOVTxsM+sHzIjJu8N9vRjMFXGM56W1MSXK",
	"0Gw4cB1HieFptjWz/mMo2kZmuG/DiqkUYWWpAUGuxjdl2YsblEzlW6AsqfirwOz//4Yqvci+AzVTWZ5I",
	"GJAvQzFS6Y1hkuNW+beJLj+hNxVGl7c3EEOpMux1aFkxiXVqJwlZMCkqMezqwDt0vuNJ5+n8giHGopZW",
	"gYDFPJ2nEIOVVIRMkryuqibxsrJlCLDFMAecbZiCmxwE/M2ga51bozSF7U5WSOg8iPtT+aFjopAtZwgC",
	"Hmt0DcSD+H5pHKsXTfQ0MzyyXL8t6hk+kZMzktsgeSdLlXPyYjzptl3Fx/fHH53BTE3sMy4ZPCAY4Svw",
	"DBpviHPYiwNLP4ddHJjxOezywEC/jWUQ91l3dPdgqOCardoYrPHnCn3LkK6d0dOVyZvvMsvjkelqfFrr",
	"Hyp1OzlL49T1NvGrHV7dDm0MSedUGRvfV33gn9EcYfqA3+UqnfLgiSv1rvGEVaR8NLjs2w+C7+PwR6Fz",
	"ttqVIKAgsiJJSpPJsjCexCJlgtUzwakFBr4IR8Psna+P067aLwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
