// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	. "cdd-go-boilerplate/internal/entity"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /dummy/sample)
	DummyEndpoint(ctx echo.Context, params DummyEndpointParams) error

	// (POST /dummy/sample)
	DummyEndpointPost(ctx echo.Context) error

	// (GET /healthcheck)
	HealthCheck(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DummyEndpoint converts echo context to params.
func (w *ServerInterfaceWrapper) DummyEndpoint(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DummyEndpointParams
	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", ctx.QueryParams(), &params.Type)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DummyEndpoint(ctx, params)
	return err
}

// DummyEndpointPost converts echo context to params.
func (w *ServerInterfaceWrapper) DummyEndpointPost(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DummyEndpointPost(ctx)
	return err
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/dummy/sample", wrapper.DummyEndpoint)
	router.POST(baseURL+"/dummy/sample", wrapper.DummyEndpointPost)
	router.GET(baseURL+"/healthcheck", wrapper.HealthCheck)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWwXKjOBD9Fap3j9iQtfeiW7Kbqs1hq1KbY8oHGdpGWZAUqfGEcfHvUy0g2A4zzkyS",
	"Oc0JjJ5ev1Z3P3kPmams0ajJg9iDQ2+N9hh+LNOUH5nRhJr4VVpbqkySMjp58EbzN58VWEl++93hBgT8",
	"loycSbfqk2vnjIO2bWPI0WdOWSYBAWuZRw4fa/QUYQeKYZlefHzkWsuaCuPUZ8wPQy8+PvTGuLXKc9Rd",
	"xOXHR9SGoo2p9UGmf/6M8ipN6LQsI2nVzKPboRsV+DrL0Pt3U3ElPd71nJOt5jHqY0ZDpwPjegLmP+QQ",
	"e7DOWHSksFeZIz+psQgCPDmlt5xJLonVtTFU6L3cTqHaGLjRlcMcxH3HNeJ7jlU8bDPrB8yIybvDfb0Y",
	"zBVxjOeltTElytBsOHAdR4nhabY1s/5jKNpGZrhvw4qpFGFlqQFBrsY3ZdmLG5RM5VugLKn4q8Ds//+G",
	"Kr3IvgM1U1meSBiQL0MxUumNYZLjVvm3iS4/oTcVRpe3NxBDqTLsdWhZMYl1aicJWTApKjHs6sA7dL7j",
	"Sefp/IIhxqKWVoGAxTydpxCDlVSETJK8rqom8bKyZQiwxTAHnG2YgpscBPzNoGudW6M0he1OVkjoPIj7",
	"U/mhY6KQLWcIAh5rdA3Eg/h+aRyrF030NDM8sly/LeoZPpGTM5LbIHknS5Vz8mI86bZdxcf3xx+dwUxN",
	"7DMuGTwgGOEr8Awab4hz2IsDSz+HXRyY8Tns8sBAv41lEPdZd3T3YKjgmq3aGKzx5wp9y5CundHTlcmb",
	"7zLL45Hpanxa6x8qdTs5S+PU9Tbxqx1e3Q5tDEnnVBkb31d94J/RHGH6gN/lKp3y4Ikr9a7xhFWkfDS4",
	"7NsPgu/j8Eehc7balSCgILIiSUqTybIwnsQiZYLVM8GpBQa+CEfD7J2vj9Ou2i8BAAD//2BQjRX8CgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
